server:
  port: 8091 # 服务端口

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8889/eureka/ # 服务注册中心地址
      defaultZone: http://wn:123456@localhost:8889/eureka/
spring:
  application:
    name: TRADE_SERVER # 服务名称

datasource: 
  type: com.alibaba.druid.pool.DruidDataSource  
  master:   
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wn?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456 
  slave: 
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wn_read?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456
    
#mybatis config   
mybatis: 
    typeAliasesPackage: com.wn.model
    mapperLocations: classpath*:com/wn/mapper/*.xml