server:
  port: 8082 # 服务端口

eureka:
  client:
#    registry-fetch-interval-seconds: 10 
    healthcheck: # 开启健康检查（依赖spring-boot-starter-actuator）
       enabled: true        
    service-url: 
     # defaultZone: http://localhost:8888/eureka/ # 服务注册中心地址]
      defaultZone: http://wn:123456@localhost:8888/eureka/
  instance: 
      preferIpAddress: true  #像eureka服务注册信息时，使用ip地址，默认使用hostname 
#      lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
#      lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）  

spring:
  application:
    name: UCENTER # 服务名称
  
  
datasource: 
  type: com.alibaba.druid.pool.DruidDataSource  
  master:   
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456 
  slave: 
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: 123456
      
#mybatis config   
mybatis: 
    typeAliasesPackage: com.wn.model
    mapperLocations: classpath*:com/wn/mapper/*.xml 
    
    
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql    
  

    
  
    